modLoader="javafml" #mandatory
loaderVersion="[25,)"
credits="Biomes O Plenty, Harry Talks,"
authors="UncleBrick"

[[mods]]
modId="unclebricksmod"
version="0.1" 
displayName="UncleBrick's Mod"
description='''
This is a Forge Mod based on several tutorial series from 
a few people on YouTube, the web, and Biomes O' Plenty.  
'''

[[dependencies.unclebricksmod]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unclebricksmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"